### PR TITLE
ConnectionProvider validated

### PR DESCRIPTION
**Pull request by simonjenga**
ConnectionProvider validated

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge it

**Comment by yegor256** [comment]
@simonjenga thanks for your contribution! Keep in mind that this framework is going to be suspended in favor of www.takes.org. Would be great if you can contribute there instead. Thanks.

**Comment by ypradhan** [comment]
@rultor

**Comment by simonjenga** [comment]
@yegor256 As usual, many thanks for sharing your knowledge and i will be joining the new projects' bandwagon shortly and makes some contributions.

**Pull request merged**
